# Generated by Django 3.0.8 on 2020-07-17 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0002_auto_20200716_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='seguindo',
            field=models.ManyToManyField(related_name='seguidores', to='pessoa.Perfil'),
        ),
    ]
