# Generated by Django 3.0.8 on 2020-07-17 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0003_auto_20200717_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='seguindo',
            field=models.ManyToManyField(null=True, related_name='seguidores', to='pessoa.Perfil'),
        ),
    ]
