# Generated by Django 3.0.8 on 2020-07-17 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0004_auto_20200717_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='seguindo',
            field=models.ManyToManyField(blank=True, null=True, related_name='seguidores', to='pessoa.Perfil'),
        ),
    ]
