# Generated by Django 3.0.8 on 2020-07-22 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0005_auto_20200717_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='foto',
            field=models.ImageField(upload_to='piadouro/imagens/'),
        ),
    ]
